name: ðŸš€ Deploy the app on push

on:
  push:
    branches:
      - prod

jobs:
  web-deploy:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ” Create env file
        run: |
          touch .env
          echo VITE_API_URL=${{ secrets.api_url_prod }} >> .env
          echo VITE_PORT=3000 >> .env
          cat .env

      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - run: npm install
      - run: npm run build

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.server_prod_host }}
          username: ${{ secrets.ftp_prod_username }}
          password: ${{ secrets.ftp_prod_password }}
          server-dir: ./public_html/
          local-dir: ./dist/
